# Generated by Django 5.2.11 on 2026-03-06 21:00

from django.db import migrations, models


def consolidate_multilingual_content(apps, schema_editor):
    Article = apps.get_model("portal", "Article")
    ErrorCode = apps.get_model("portal", "ErrorCode")
    Brand = apps.get_model("portal", "Brand")
    Category = apps.get_model("portal", "Category")
    Device = apps.get_model("portal", "Device")

    for model in (Brand, Category, Device):
        for obj in model.objects.all():
            obj.name_ru = obj.name_ru or obj.name
            obj.name_en = obj.name_en or obj.name
            obj.seo_title_ru = obj.seo_title_ru or obj.seo_title
            obj.seo_title_en = obj.seo_title_en or obj.seo_title
            obj.meta_description_ru = obj.meta_description_ru or obj.meta_description
            obj.meta_description_en = obj.meta_description_en or obj.meta_description
            if hasattr(obj, "description"):
                obj.description_ru = obj.description_ru or obj.description
                obj.description_en = obj.description_en or obj.description
            if hasattr(obj, "device_type"):
                obj.device_type_ru = obj.device_type_ru or obj.device_type
                obj.device_type_en = obj.device_type_en or obj.device_type
            obj.save()

    article_slugs = Article.objects.values_list("slug", flat=True).distinct()
    for slug in article_slugs:
        records = list(Article.objects.filter(slug=slug).order_by("created_at", "id"))
        if not records:
            continue
        primary = next((item for item in records if item.language == "uk"), records[0])
        for record in records:
            if record.language == "ru":
                primary.title_ru = record.title
                primary.excerpt_ru = record.excerpt
                primary.content_ru = record.content
                primary.seo_title_ru = record.seo_title
                primary.meta_description_ru = record.meta_description
            elif record.language == "en":
                primary.title_en = record.title
                primary.excerpt_en = record.excerpt
                primary.content_en = record.content
                primary.seo_title_en = record.seo_title
                primary.meta_description_en = record.meta_description
            elif record.language == "uk":
                primary.title = record.title
                primary.excerpt = record.excerpt
                primary.content = record.content
                primary.seo_title = record.seo_title
                primary.meta_description = record.meta_description
        primary.title_ru = primary.title_ru or primary.title
        primary.title_en = primary.title_en or primary.title
        primary.excerpt_ru = primary.excerpt_ru or primary.excerpt
        primary.excerpt_en = primary.excerpt_en or primary.excerpt
        primary.content_ru = primary.content_ru or primary.content
        primary.content_en = primary.content_en or primary.content
        primary.seo_title_ru = primary.seo_title_ru or primary.seo_title
        primary.seo_title_en = primary.seo_title_en or primary.seo_title
        primary.meta_description_ru = primary.meta_description_ru or primary.meta_description
        primary.meta_description_en = primary.meta_description_en or primary.meta_description
        primary.language = "uk"
        primary.save()
        for record in records:
            if record.pk != primary.pk:
                record.delete()

    error_slugs = ErrorCode.objects.values_list("slug", flat=True).distinct()
    for slug in error_slugs:
        records = list(ErrorCode.objects.filter(slug=slug).order_by("created_at", "id"))
        if not records:
            continue
        primary = next((item for item in records if item.language == "uk"), records[0])
        for record in records:
            if record.language == "ru":
                primary.title_ru = record.title
                primary.description_ru = record.description
                primary.causes_ru = record.causes
                primary.solutions_ru = record.solutions
                primary.seo_title_ru = record.seo_title
                primary.meta_description_ru = record.meta_description
            elif record.language == "en":
                primary.title_en = record.title
                primary.description_en = record.description
                primary.causes_en = record.causes
                primary.solutions_en = record.solutions
                primary.seo_title_en = record.seo_title
                primary.meta_description_en = record.meta_description
            elif record.language == "uk":
                primary.title = record.title
                primary.description = record.description
                primary.causes = record.causes
                primary.solutions = record.solutions
                primary.seo_title = record.seo_title
                primary.meta_description = record.meta_description
        primary.title_ru = primary.title_ru or primary.title
        primary.title_en = primary.title_en or primary.title
        primary.description_ru = primary.description_ru or primary.description
        primary.description_en = primary.description_en or primary.description
        primary.causes_ru = primary.causes_ru or primary.causes
        primary.causes_en = primary.causes_en or primary.causes
        primary.solutions_ru = primary.solutions_ru or primary.solutions
        primary.solutions_en = primary.solutions_en or primary.solutions
        primary.seo_title_ru = primary.seo_title_ru or primary.seo_title
        primary.seo_title_en = primary.seo_title_en or primary.seo_title
        primary.meta_description_ru = primary.meta_description_ru or primary.meta_description
        primary.meta_description_en = primary.meta_description_en or primary.meta_description
        primary.language = "uk"
        primary.save()
        for record in records:
            if record.pk != primary.pk:
                record.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="article",
            name="unique_article_slug_per_language",
        ),
        migrations.RemoveConstraint(
            model_name="errorcode",
            name="unique_error_slug_per_language",
        ),
        migrations.AddField(
            model_name="article",
            name="content_en",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="article",
            name="content_ru",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="article",
            name="excerpt_en",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="article",
            name="excerpt_ru",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="article",
            name="meta_description_en",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="article",
            name="meta_description_ru",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="article",
            name="seo_title_en",
            field=models.CharField(default="", max_length=160),
        ),
        migrations.AddField(
            model_name="article",
            name="seo_title_ru",
            field=models.CharField(default="", max_length=160),
        ),
        migrations.AddField(
            model_name="article",
            name="title_en",
            field=models.CharField(default="", max_length=220),
        ),
        migrations.AddField(
            model_name="article",
            name="title_ru",
            field=models.CharField(default="", max_length=220),
        ),
        migrations.AddField(
            model_name="brand",
            name="description_en",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="brand",
            name="description_ru",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="brand",
            name="meta_description_en",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="brand",
            name="meta_description_ru",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="brand",
            name="name_en",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AddField(
            model_name="brand",
            name="name_ru",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AddField(
            model_name="brand",
            name="seo_title_en",
            field=models.CharField(default="", max_length=160),
        ),
        migrations.AddField(
            model_name="brand",
            name="seo_title_ru",
            field=models.CharField(default="", max_length=160),
        ),
        migrations.AddField(
            model_name="category",
            name="description_en",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="category",
            name="description_ru",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_description_en",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_description_ru",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AddField(
            model_name="category",
            name="seo_title_en",
            field=models.CharField(default="", max_length=160),
        ),
        migrations.AddField(
            model_name="category",
            name="seo_title_ru",
            field=models.CharField(default="", max_length=160),
        ),
        migrations.AddField(
            model_name="device",
            name="description_en",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="device",
            name="description_ru",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="device",
            name="device_type_en",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AddField(
            model_name="device",
            name="device_type_ru",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AddField(
            model_name="device",
            name="meta_description_en",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="device",
            name="meta_description_ru",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="device",
            name="name_en",
            field=models.CharField(default="", max_length=160),
        ),
        migrations.AddField(
            model_name="device",
            name="name_ru",
            field=models.CharField(default="", max_length=160),
        ),
        migrations.AddField(
            model_name="device",
            name="seo_title_en",
            field=models.CharField(default="", max_length=160),
        ),
        migrations.AddField(
            model_name="device",
            name="seo_title_ru",
            field=models.CharField(default="", max_length=160),
        ),
        migrations.AddField(
            model_name="errorcode",
            name="causes_en",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="errorcode",
            name="causes_ru",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="errorcode",
            name="description_en",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="errorcode",
            name="description_ru",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="errorcode",
            name="meta_description_en",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="errorcode",
            name="meta_description_ru",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="errorcode",
            name="seo_title_en",
            field=models.CharField(default="", max_length=160),
        ),
        migrations.AddField(
            model_name="errorcode",
            name="seo_title_ru",
            field=models.CharField(default="", max_length=160),
        ),
        migrations.AddField(
            model_name="errorcode",
            name="solutions_en",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="errorcode",
            name="solutions_ru",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="errorcode",
            name="title_en",
            field=models.CharField(default="", max_length=220),
        ),
        migrations.AddField(
            model_name="errorcode",
            name="title_ru",
            field=models.CharField(default="", max_length=220),
        ),
        migrations.RunPython(consolidate_multilingual_content, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="article",
            name="language",
        ),
        migrations.RemoveField(
            model_name="device",
            name="language",
        ),
        migrations.RemoveField(
            model_name="errorcode",
            name="language",
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="article",
            name="excerpt",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="article",
            name="meta_description",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="article",
            name="seo_title",
            field=models.CharField(default="", max_length=160),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(default="", max_length=220),
        ),
        migrations.AlterField(
            model_name="brand",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="brand",
            name="meta_description",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="brand",
            name="seo_title",
            field=models.CharField(default="", max_length=160),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_description",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="category",
            name="seo_title",
            field=models.CharField(default="", max_length=160),
        ),
        migrations.AlterField(
            model_name="device",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_type",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="device",
            name="meta_description",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.CharField(default="", max_length=160),
        ),
        migrations.AlterField(
            model_name="device",
            name="seo_title",
            field=models.CharField(default="", max_length=160),
        ),
        migrations.AlterField(
            model_name="errorcode",
            name="causes",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="errorcode",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="errorcode",
            name="meta_description",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="errorcode",
            name="seo_title",
            field=models.CharField(default="", max_length=160),
        ),
        migrations.AlterField(
            model_name="errorcode",
            name="slug",
            field=models.SlugField(max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name="errorcode",
            name="solutions",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="errorcode",
            name="title",
            field=models.CharField(default="", max_length=220),
        ),
    ]
