# Generated by Django 5.2.11 on 2026-03-06 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_article_unique_article_slug_per_language_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-featured', '-created_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position', 'name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['name'], 'verbose_name': 'Устройство', 'verbose_name_plural': 'Устройства'},
        ),
        migrations.AlterModelOptions(
            name='errorcode',
            options={'ordering': ['brand_name', 'appliance_type', 'code'], 'verbose_name': 'Код ошибки', 'verbose_name_plural': 'Коды ошибок'},
        ),
        migrations.AddField(
            model_name='errorcode',
            name='appliance_slug',
            field=models.SlugField(default='', max_length=140, verbose_name='Слаг типа техники'),
        ),
        migrations.AddField(
            model_name='errorcode',
            name='appliance_type',
            field=models.CharField(default='', max_length=120, verbose_name='Тип техники (укр.)'),
        ),
        migrations.AddField(
            model_name='errorcode',
            name='appliance_type_en',
            field=models.CharField(default='', max_length=120, verbose_name='Тип техники (англ.)'),
        ),
        migrations.AddField(
            model_name='errorcode',
            name='appliance_type_ru',
            field=models.CharField(default='', max_length=120, verbose_name='Тип техники (рус.)'),
        ),
        migrations.AddField(
            model_name='errorcode',
            name='brand_name',
            field=models.CharField(default='', max_length=120, verbose_name='Бренд (укр.)'),
        ),
        migrations.AddField(
            model_name='errorcode',
            name='brand_name_en',
            field=models.CharField(default='', max_length=120, verbose_name='Бренд (англ.)'),
        ),
        migrations.AddField(
            model_name='errorcode',
            name='brand_name_ru',
            field=models.CharField(default='', max_length=120, verbose_name='Бренд (рус.)'),
        ),
        migrations.AddField(
            model_name='errorcode',
            name='brand_slug',
            field=models.SlugField(default='', max_length=140, verbose_name='Слаг бренда'),
        ),
        migrations.AlterField(
            model_name='article',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='portal.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='portal.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='', verbose_name='Контент (укр.)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_en',
            field=models.TextField(default='', verbose_name='Контент (англ.)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_ru',
            field=models.TextField(default='', verbose_name='Контент (рус.)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='article',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='portal.device', verbose_name='Устройство'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(default='', verbose_name='Краткое описание (укр.)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt_en',
            field=models.TextField(default='', verbose_name='Краткое описание (англ.)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt_ru',
            field=models.TextField(default='', verbose_name='Краткое описание (рус.)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемое'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(blank=True, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_description',
            field=models.CharField(default='', max_length=255, verbose_name='Meta description (укр.)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_description_en',
            field=models.CharField(default='', max_length=255, verbose_name='Meta description (англ.)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_description_ru',
            field=models.CharField(default='', max_length=255, verbose_name='Meta description (рус.)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_title',
            field=models.CharField(default='', max_length=160, verbose_name='SEO-заголовок (укр.)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_title_en',
            field=models.CharField(default='', max_length=160, verbose_name='SEO-заголовок (англ.)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_title_ru',
            field=models.CharField(default='', max_length=160, verbose_name='SEO-заголовок (рус.)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=220, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=220, verbose_name='Заголовок (укр.)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_en',
            field=models.CharField(default='', max_length=220, verbose_name='Заголовок (англ.)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_ru',
            field=models.CharField(default='', max_length=220, verbose_name='Заголовок (рус.)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(default='', verbose_name='Описание (укр.)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description_en',
            field=models.TextField(default='', verbose_name='Описание (англ.)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description_ru',
            field=models.TextField(default='', verbose_name='Описание (рус.)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.URLField(blank=True, verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='meta_description',
            field=models.CharField(default='', max_length=255, verbose_name='Meta description (укр.)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='meta_description_en',
            field=models.CharField(default='', max_length=255, verbose_name='Meta description (англ.)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='meta_description_ru',
            field=models.CharField(default='', max_length=255, verbose_name='Meta description (рус.)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(default='', max_length=120, verbose_name='Название (укр.)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name_en',
            field=models.CharField(default='', max_length=120, verbose_name='Название (англ.)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name_ru',
            field=models.CharField(default='', max_length=120, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='seo_title',
            field=models.CharField(default='', max_length=160, verbose_name='SEO-заголовок (укр.)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='seo_title_en',
            field=models.CharField(default='', max_length=160, verbose_name='SEO-заголовок (англ.)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='seo_title_ru',
            field=models.CharField(default='', max_length=160, verbose_name='SEO-заголовок (рус.)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='website',
            field=models.URLField(blank=True, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='', verbose_name='Описание (укр.)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_en',
            field=models.TextField(default='', verbose_name='Описание (англ.)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_ru',
            field=models.TextField(default='', verbose_name='Описание (рус.)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.CharField(default='', max_length=255, verbose_name='Meta description (укр.)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description_en',
            field=models.CharField(default='', max_length=255, verbose_name='Meta description (англ.)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description_ru',
            field=models.CharField(default='', max_length=255, verbose_name='Meta description (рус.)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=120, verbose_name='Название (укр.)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(default='', max_length=120, verbose_name='Название (англ.)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(default='', max_length=120, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_title',
            field=models.CharField(default='', max_length=160, verbose_name='SEO-заголовок (укр.)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_title_en',
            field=models.CharField(default='', max_length=160, verbose_name='SEO-заголовок (англ.)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_title_ru',
            field=models.CharField(default='', max_length=160, verbose_name='SEO-заголовок (рус.)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='device',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='portal.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='portal.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(default='', verbose_name='Описание (укр.)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='description_en',
            field=models.TextField(default='', verbose_name='Описание (англ.)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='description_ru',
            field=models.TextField(default='', verbose_name='Описание (рус.)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(default='', max_length=120, verbose_name='Тип устройства (укр.)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type_en',
            field=models.CharField(default='', max_length=120, verbose_name='Тип устройства (англ.)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type_ru',
            field=models.CharField(default='', max_length=120, verbose_name='Тип устройства (рус.)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='meta_description',
            field=models.CharField(default='', max_length=255, verbose_name='Meta description (укр.)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='meta_description_en',
            field=models.CharField(default='', max_length=255, verbose_name='Meta description (англ.)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='meta_description_ru',
            field=models.CharField(default='', max_length=255, verbose_name='Meta description (рус.)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='', max_length=160, verbose_name='Название (укр.)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name_en',
            field=models.CharField(default='', max_length=160, verbose_name='Название (англ.)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name_ru',
            field=models.CharField(default='', max_length=160, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='seo_title',
            field=models.CharField(default='', max_length=160, verbose_name='SEO-заголовок (укр.)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='seo_title_en',
            field=models.CharField(default='', max_length=160, verbose_name='SEO-заголовок (англ.)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='seo_title_ru',
            field=models.CharField(default='', max_length=160, verbose_name='SEO-заголовок (рус.)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='slug',
            field=models.SlugField(max_length=160, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_codes', to='portal.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='causes',
            field=models.TextField(default='', verbose_name='Причины (укр.)'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='causes_en',
            field=models.TextField(default='', verbose_name='Причины (англ.)'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='causes_ru',
            field=models.TextField(default='', verbose_name='Причины (рус.)'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='code',
            field=models.CharField(max_length=40, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='description',
            field=models.TextField(default='', verbose_name='Описание (укр.)'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='description_en',
            field=models.TextField(default='', verbose_name='Описание (англ.)'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='description_ru',
            field=models.TextField(default='', verbose_name='Описание (рус.)'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_codes', to='portal.device', verbose_name='Устройство'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='meta_description',
            field=models.CharField(default='', max_length=255, verbose_name='Meta description (укр.)'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='meta_description_en',
            field=models.CharField(default='', max_length=255, verbose_name='Meta description (англ.)'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='meta_description_ru',
            field=models.CharField(default='', max_length=255, verbose_name='Meta description (рус.)'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='seo_title',
            field=models.CharField(default='', max_length=160, verbose_name='SEO-заголовок (укр.)'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='seo_title_en',
            field=models.CharField(default='', max_length=160, verbose_name='SEO-заголовок (англ.)'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='seo_title_ru',
            field=models.CharField(default='', max_length=160, verbose_name='SEO-заголовок (рус.)'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='slug',
            field=models.SlugField(max_length=220, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='solutions',
            field=models.TextField(default='', verbose_name='Решения (укр.)'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='solutions_en',
            field=models.TextField(default='', verbose_name='Решения (англ.)'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='solutions_ru',
            field=models.TextField(default='', verbose_name='Решения (рус.)'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='title',
            field=models.CharField(default='', max_length=220, verbose_name='Заголовок (укр.)'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='title_en',
            field=models.CharField(default='', max_length=220, verbose_name='Заголовок (англ.)'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='title_ru',
            field=models.CharField(default='', max_length=220, verbose_name='Заголовок (рус.)'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
