# Generated by Django 5.2.11 on 2026-03-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_repairbrand_slug_alter_repairmodel_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='coverage_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Покриття ремонту (англ.)'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='coverage_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Покриття ремонту (рус.)'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='notes_en',
            field=models.JSONField(blank=True, default=list, verbose_name='Нотатки (англ.)'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='notes_ru',
            field=models.JSONField(blank=True, default=list, verbose_name='Нотатки (рус.)'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='product_description_en',
            field=models.TextField(blank=True, default='', verbose_name='Опис товару (англ.)'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='product_description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Опис товару (рус.)'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='repair_tips_en',
            field=models.JSONField(blank=True, default=list, verbose_name='Поради з ремонту (англ.)'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='repair_tips_ru',
            field=models.JSONField(blank=True, default=list, verbose_name='Поради з ремонту (рус.)'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='short_specs_en',
            field=models.JSONField(blank=True, default=dict, verbose_name='Короткі характеристики (англ.)'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='short_specs_ru',
            field=models.JSONField(blank=True, default=dict, verbose_name='Короткі характеристики (рус.)'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='source_links_en',
            field=models.JSONField(blank=True, default=list, verbose_name='Джерела (англ.)'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='source_links_ru',
            field=models.JSONField(blank=True, default=list, verbose_name='Джерела (рус.)'),
        ),
    ]
