# Generated by Django 5.2.11 on 2026-03-06 22:26

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0004_repairappliancetype_alter_errorcode_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminArticle',
            fields=[
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portal.article',),
        ),
    ]
